language: java
env: MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=192m" GRADLE_OPTS="-Xmx1024m -XX:MaxPermSize=192m" TERM="dumb"
jdk:
  - openjdk8
services:
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo chsh --shell $(which bash)
script:
    - './gradlew clean build && bash run-docker-vault-tests.sh'
addons:
  hostname: rdbuild
  apt:
    packages:
    - make
    - zip
    - unzip
# whitelist
branches:
  only:
    - master